"""Shared markdown helpers."""

from __future__ import annotations

from datetime import datetime, timezone

SEV_LABEL = {"L": "Low", "M": "Medium", "H": "High", "C": "Critical"}
CAT_LABEL = {
    "security": "Security exposure",
    "timeline": "Timeline",
    "workaround": "Workaround / tactical debt",
    "legal-reg": "Legal & regulatory",
    "cost": "Cost",
    "operational": "Operational",
}
STATE_LABEL = {
    "satisfied": "Satisfied",
    "contradiction": "CONTRADICTION",
    "gap": "Gap",
    "unpinned": "Unpinned",
    "not-applicable": "-",
}


def stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def esc(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def header(project, intake, recon, doc: str) -> str:
    return (
        f"# {doc} - {intake.title}\n\n"
        f"**Project** `{project.id}` &nbsp;|&nbsp; "
        f"**Date** {stamp()} &nbsp;|&nbsp; "
        f"**Complexity** {intake.tier} &nbsp;|&nbsp; "
        f"**Verdict** {recon.verdict.replace('-', ' ').title()}\n\n"
        f"> This document was generated by the Enterprise Architect Strategy framework "
        f"from the brief held at `brief.md` in this project. It reads no other project.\n\n"
    )


def anchors_table(anchors) -> list[str]:
    if not anchors:
        return ["_No volumetric anchors declared for this position._", ""]
    out = ["| Anchor | Unit | Prod | RTL | Dev-Test | Sizing-critical |",
           "|---|---|---|---|---|---|"]
    for a in anchors:
        crit = "**yes**" if a.critical else "no"
        out.append(
            f"| {esc(a.metric)} | {esc(a.unit)} | {esc(a.prod)} | {esc(a.rtl)} "
            f"| {esc(a.devtest)} | {crit} |"
        )
    notes = [a for a in anchors if a.note]
    if notes:
        out += ["", "**Notes on specific anchors**", ""]
        out += [f"- *{esc(a.metric)}* - {a.note}" for a in notes]
    out.append("")
    return out


def risks_table(risks) -> list[str]:
    if not risks:
        return ["_No risks recorded._", ""]
    out = ["| ID | Category | Severity | Risk | Mitigation |", "|---|---|---|---|---|"]
    for r in sorted(risks, key=lambda x: -x.rank):
        tag = " *(emergent)*" if r.emergent else ""
        out.append(
            f"| {r.id} | {CAT_LABEL.get(r.category, r.category)} | {SEV_LABEL.get(r.severity, r.severity)} "
            f"| {esc(r.statement)}{tag} | {esc(r.mitigation)} |"
        )
    out.append("")
    return out


def questions_table(questions) -> list[str]:
    if not questions:
        return ["_No open questions._", ""]
    out = ["| ID | Blocking | Owner | Question |", "|---|---|---|---|"]
    for q in sorted(questions, key=lambda x: (not x.blocking, x.id)):
        out.append(
            f"| {q.id} | {'**yes**' if q.blocking else 'no'} | {esc(q.owner_role)} "
            f"| {esc(q.question)} |"
        )
    out.append("")
    return out
