#!/usr/bin/env python3
"""Generate the nine validator SKILL.md files from the catalogue.

The skills and the engine must never disagree about what a domain covers, so
the validator skills are generated rather than written by hand. Change the
catalogue, re-run this, and the skills follow.

    python3 tools/gen_skills.py

The orchestrator and run skills are hand-written and are not touched here.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from eas.catalogue import Catalogue  # noqa: E402

SKILLS_DIR = ROOT / ".claude" / "skills"
GENERATED_MARK = "<!-- generated by tools/gen_skills.py - edit the catalogue, not this file -->"


def render(cat: Catalogue, dom) -> str:
    options = cat.options_for(dom.key)
    caps_provided = sorted({c for o in options for c in o.provides})
    caps_required = sorted({c for o in options for c in o.requires})

    L: list[str] = []
    L += [
        "---",
        f"name: {dom.skill}",
        "description: >-",
        f"  {dom.name} for the Enterprise Architect Strategy framework. Use when base-plating a",
        f"  direction and this domain needs validating: {dom.scope.lower().rstrip('.')}.",
        "  Produces the four artefacts - checklist, further-questioning, per-environment",
        "  volumetric anchors, and cross-domain hooks - plus a ranked set of defensible options",
        "  for the orchestrator to reconcile.",
        "---",
        "",
        GENERATED_MARK,
        "",
        f"# {dom.name}",
        "",
        f"**Domain code** `{dom.code}` &nbsp;|&nbsp; **Gating order** {dom.order} of 9",
        "",
        f"{dom.scope}",
        "",
        "## What this skill produces",
        "",
        "Exactly four artefacts, because that is what keeps runs comparable and the "
        "orchestrator's job tractable:",
        "",
        "| Artefact | Purpose |",
        "|---|---|",
        "| **Checklist** | The did-we-cover-it surface. Every item is verified three times - "
        "Prod, RTL and Dev-Test. |",
        "| **Further-questioning** | Open items needing a stakeholder answer or research before "
        "the position is safe. A blocking item gates a decision. |",
        "| **Volumetric anchors** | The numbers that must be pinned per environment. An "
        "unpinned sizing-critical anchor blocks sizing. |",
        "| **Cross-domain hooks** | What this domain imposes on others and requires from them. "
        "This is the orchestrator's raw material. |",
        "",
        "Plus the thing that makes the framework work end to end: **a ranked set of options**, "
        "not a single answer. The orchestrator decides which one survives contact with the "
        "other eight domains.",
        "",
        "## The three lenses, applied inside this domain",
        "",
        "- **Environment.** Every checklist item and every anchor is evaluated for Prod, RTL "
        "and Dev-Test separately. RTL is first-class, not prod-lite. The highest-value question "
        "this lens forces: what real or quasi-real data touches non-prod, and under what "
        "control?",
        "- **Integration.** Verify security *at every interface*, not per component in "
        "isolation. Each edge between two objects has its own trust boundary, authN/authZ, "
        "transport, logging and residency.",
        "- **Volumetric.** Turn qualitative positions into quantities. \"We will allow outbound "
        "to partners\" becomes \"N allow-listed FQDNs, X GB/day egress, split P/RTL/D-T\" - "
        "which is what makes it sizeable, costable and defensible.",
        "",
        "## How to run this domain",
        "",
        "```bash",
        "# The whole framework, this domain included, against a brief:",
        "python3 -m eas new --brief path/to/brief.md",
        "",
        "# This domain's options, scores and rationale for an existing project:",
        f"cat projects/<project-id>/options/{dom.key}.md",
        f"cat projects/<project-id>/outputs/lld/{dom.key}.md",
        "",
        "# Fix this domain to a specific option and re-reconcile:",
        f"python3 -m eas set <project-id> {dom.key} <OPTION-ID>",
        "```",
        "",
        "When working a brief by hand rather than through the engine, follow the same shape: "
        "pick the option that fits, work its checklist across all three environments, record "
        "the questions with owners, pin what you can, and hand the hooks to "
        "`orchestrate-baseplate`.",
        "",
        f"## Options this domain offers ({len(options)})",
        "",
    ]

    for o in options:
        L += [
            f"### `{o.id}` - {o.name}",
            "",
            f"*{o.posture.title()} posture &middot; {o.effort_weeks} weeks (band {o.effort_band}) "
            f"&middot; cost band {o.cost_band} &middot; security {o.security_score}/5 &middot; "
            f"regulatory evidencing {o.reg_score}/5 &middot; operational burden {o.ops_burden}/5*",
            "",
            o.summary,
            "",
        ]
        if o.provides:
            L += ["**Imposes on / gives others:** " + ", ".join(f"`{c}`" for c in o.provides), ""]
        if o.requires:
            L += ["**Requires from others:** " + ", ".join(f"`{c}`" for c in o.requires), ""]
        if o.checklist:
            L += ["**Checklist**", ""] + [f"- {c}" for c in o.checklist] + [""]
        if o.questions:
            L += ["**Further-questioning**", ""]
            L += [f"- {'**[blocking]** ' if q.blocking else ''}{q.question} "
                  f"*(owner: {q.owner_role})*" for q in o.questions]
            L += [""]
        if o.anchors:
            L += ["**Volumetric anchors** (pin each for Prod / RTL / Dev-Test)", "",
                  "| Anchor | Unit | Sizing-critical |", "|---|---|---|"]
            L += [f"| {a.metric} | {a.unit} | {'yes' if a.critical else 'no'} |"
                  for a in o.anchors]
            L += [""]
        if o.risks:
            L += ["**Risks this option carries**", ""]
            L += [f"- **{r.severity} / {r.category}** - {r.statement} "
                  f"*Mitigation:* {r.mitigation}" for r in o.risks]
            L += [""]
        if o.controls:
            L += ["**Control mapping:** " + ", ".join(f"`{c}`" for c in o.controls), ""]

    L += ["## Capability vocabulary used by this domain", "",
          "These are the shared tags the orchestrator reconciles on. They are not free text - "
          "see `catalogue/capabilities.json`.", "",
          "**Supplied by options here:**", ""]
    L += [f"- `{c}` - {cat.capabilities[c]['desc']}" for c in caps_provided]
    L += ["", "**Needed from other domains:**", ""]
    L += ([f"- `{c}` - {cat.capabilities[c]['desc']} *(owned by "
           f"{cat.capabilities[c]['owner']})*" for c in caps_required] or ["- _nothing_"])

    L += ["", "## Where this domain's content lives", "",
          f"- Options: `catalogue/options/{dom.key}.json`",
          "- Shared capability vocabulary: `catalogue/capabilities.json`",
          "- Cross-domain rules that involve this domain: `catalogue/compat.json`", "",
          "Edit the catalogue, then run `python3 tools/gen_skills.py` to regenerate this file "
          "and `python3 -m eas lint` to check the catalogue is still coherent.", ""]
    return "\n".join(L)


def main() -> int:
    cat = Catalogue()
    problems = cat.lint()
    if problems:
        print("refusing to generate from an incoherent catalogue:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    for dom in sorted(cat.domains, key=lambda d: d.order):
        out = SKILLS_DIR / dom.skill
        out.mkdir(parents=True, exist_ok=True)
        (out / "SKILL.md").write_text(render(cat, dom), encoding="utf-8")
        print(f"wrote {out / 'SKILL.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
