#!/usr/bin/env python3
"""Generate the security architecture team from the org catalogue.

Three tiers, eighty agents:

    1  master-architect      evaluates and reconciles across domains
   12  architect-<domain>    orchestrates, compiles, validates, sense-checks
   67  sme-<capability>      capability depth, working in isolation

The routing and escalation protocol is stamped verbatim into every agent from
`catalogue/org/hierarchy.json`, so an SME's understanding of when to escalate
cannot drift from its Architect's understanding of when to accept.

    python3 tools/gen_agents.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS = ROOT / ".claude" / "agents"
ORG = ROOT / "catalogue" / "org"
MARK = "<!-- generated by tools/gen_agents.py - edit catalogue/org/, not this file -->"

SME_TOOLS = "Read, Grep, Glob, WebSearch, WebFetch"
ARCHITECT_TOOLS = "Read, Grep, Glob, Bash, WebSearch, WebFetch"
MASTER_TOOLS = "Read, Write, Edit, Bash, Grep, Glob, WebSearch, WebFetch"


def load() -> tuple[dict, dict[str, list[dict]]]:
    hierarchy = json.loads((ORG / "hierarchy.json").read_text(encoding="utf-8"))
    smes: dict[str, list[dict]] = {}
    for dom in hierarchy["domains"]:
        path = ORG / "smes" / f"{dom['id']}.json"
        if not path.is_file():
            raise SystemExit(f"missing SME file for domain {dom['id']}: {path}")
        raw = json.loads(path.read_text(encoding="utf-8"))
        if raw["domain"] != dom["id"]:
            raise SystemExit(f"{path} declares domain {raw['domain']!r}, expected {dom['id']!r}")
        smes[dom["id"]] = raw["smes"]
    return hierarchy, smes


def bullets(items: list[str], prefix: str = "- ") -> list[str]:
    return [f"{prefix}{i}" for i in items]


# --------------------------------------------------------------------------
# SME agents
# --------------------------------------------------------------------------

def render_sme(h: dict, dom: dict, sme: dict, peers: dict[str, str]) -> str:
    proto = h["protocols"]
    art = proto["artefact"]["sme"]
    peer_lines = [f"- `sme-{p}` — {peers[p]}" for p in sme.get("peers", []) if p in peers]

    L = [
        "---",
        f"name: sme-{sme['id']}",
        "description: >-",
        f"  {sme['name']} SME within the {dom['name']} domain. Use when a question needs",
        f"  capability depth on {sme['name'].lower()} specifically. Works in isolation and returns",
        "  a position, the assumptions it refused to make, and the questions that must be answered",
        "  before its position is safe to rely on. Routing requests go back to",
        f"  `architect-{dom['id']}`, never directly to another SME.",
        f"tools: {SME_TOOLS}",
        "---",
        "",
        MARK,
        "",
        f"# {sme['name']}",
        "",
        f"**Tier 2 — SME** &nbsp;|&nbsp; **Domain** {dom['name']} (`{dom['code']}`) "
        f"&nbsp;|&nbsp; **Reports to** `architect-{dom['id']}`",
        "",
        f"{sme['owns']}",
        "",
        "## You are authoritative on",
        "",
        *bullets(sme["authoritative_on"]),
        "",
        "## How you work",
        "",
        *[f"{i}. {rule}" for i, rule in enumerate(proto["sme"], start=1)],
        "",
        "## What you must never assume",
        "",
        "These are the specific things that look settled and are not. Where one applies and you "
        "have not been told the answer, it becomes a question in your output — never a "
        "placeholder value and never a reasonable-sounding guess.",
        "",
        *bullets(sme["never_assume"]),
        "",
        "## Questions you always put",
        "",
        "| Question | Owner |",
        "|---|---|",
        *[f"| {q['q']} | {q['of']} |" for q in sme["must_ask"]],
        "",
        "## Routing",
        "",
        "### Same domain — request via your Architect",
        "",
    ]
    L += peer_lines or ["- _No same-domain peers registered for this capability._"]
    L += [
        "",
        "You do not contact a peer yourself. Return a routing request naming the SME and the "
        "specific question, and let `architect-" + dom["id"] + "` decide whether to make it.",
        "",
        "### Cross domain — escalate, do not resolve",
        "",
        "Return these to your Architect as dependencies. They go to the Master Architect, not to "
        "you, and you must not assume an answer in the meantime:",
        "",
        *bullets(sme["escalate_when"]),
        "",
        "## What you return",
        "",
        *[f"{i}. **{part}**" for i, part in enumerate(art, start=1)],
        "",
        "Concretely, this capability produces:",
        "",
        *bullets(sme["produces"]),
        "",
        "---",
        "",
        f"*Domain scope: {dom['scope']}*",
        "",
        "*Isolation is deliberate. You have been engaged for depth in one capability; a position "
        "you offer outside it carries none of that depth and displaces the SME who would have "
        "given a better one.*",
        "",
    ]
    return "\n".join(L)


# --------------------------------------------------------------------------
# Domain Architect agents
# --------------------------------------------------------------------------

def render_architect(h: dict, dom: dict, smes: list[dict], all_domains: dict[str, dict]) -> str:
    proto = h["protocols"]
    art = proto["artefact"]["domain_architect"]
    esc = proto["escalation"]

    sme_rows = [f"| `sme-{s['id']}` | {s['name']} | {s['owns']} |" for s in smes]
    interfaces = [f"- **{all_domains[d]['name']}** (`architect-{d}`) — "
                  f"{all_domains[d]['scope']}" for d in dom.get("interfaces_with", [])
                  if d in all_domains]
    eas = dom.get("eas_domains", [])

    L = [
        "---",
        f"name: architect-{dom['id']}",
        "description: >-",
        f"  {dom['name']} Architect. Use to orchestrate this domain: fan out to its SMEs, compile",
        "  their positions into one domain position, validate them against each other for",
        "  interoperability, and surface the questions that must be asked rather than assumed.",
        f"  Owns {dom['scope'][:110].rstrip('.')}. Escalates to `master-architect` only for",
        "  cross-domain dependencies.",
        f"tools: {ARCHITECT_TOOLS}",
        "---",
        "",
        MARK,
        "",
        f"# {dom['name']} Architect",
        "",
        f"**Tier 1 — Domain Architect** &nbsp;|&nbsp; **Code** `{dom['code']}` "
        f"&nbsp;|&nbsp; **Reports to** `master-architect` &nbsp;|&nbsp; "
        f"**SMEs** {len(smes)}",
        "",
        f"{dom['scope']}",
        "",
        "You are an orchestrator, a compiler, a validator and an interoperability sense-checker. "
        "You are not a deeper SME. Your value is in what you notice between your SMEs' positions "
        "and in the questions you refuse to answer on their behalf.",
        "",
        "## Your SMEs",
        "",
        "| Agent | Capability | Owns |",
        "|---|---|---|",
        *sme_rows,
        "",
        "## How you work",
        "",
        *[f"{i}. {rule}" for i, rule in enumerate(proto["domain_architect"], start=1)],
        "",
        "### Fan out",
        "",
        "Engage only the SMEs the request actually touches — engaging all of them on a narrow "
        "question produces noise that hides the real finding. Each works in isolation: do not "
        "brief one with another's output before both have reported, because a primed SME "
        "confirms rather than assesses.",
        "",
        "### Compile",
        "",
        "Reconcile into a single domain position. Where two SMEs disagree, the disagreement is "
        "the finding — do not split the difference. Identify the fact that separates them and "
        "route it back as a specific question.",
        "",
        "### Validate",
        "",
        "Check every SME position against the others in this domain. A position that is correct "
        "in isolation and incompatible with a peer's is a defect. Look particularly for:",
        "",
        "- Two SMEs assuming the other will implement the same control.",
        "- A control one SME relies on that another has recorded as detect-only, exempted, or "
        "not yet enforcing.",
        "- A number one SME used that another SME owns and has not pinned.",
        "",
        "### Sense-check what was not said",
        "",
        "An SME that raised no questions against a thin brief has assumed something. Ask what. "
        "Silence in a domain artefact is the most common route to an unexamined assumption "
        "reaching a design.",
        "",
    ] + ([
        "## Cloud and traditional infrastructure",
        "",
        h["cloud_vs_traditional"],
        "",
    ] if dom["id"] in ("cloud", "infra") else []) + [
        "## Escalation",
        "",
        "### Resolve inside this domain",
        "",
        *bullets(esc["stays_in_domain"]),
        "",
        "### Escalate to `master-architect`",
        "",
        *bullets(esc["goes_to_master"]),
        "",
        "Escalate with the specific dependency, the SME position that created it, and what you "
        "need back. Never escalate a whole domain output and ask the Master Architect to find "
        "the dependency in it.",
        "",
        "### Domains you interface with most",
        "",
        *(interfaces or ["- _None registered._"]),
        "",
        "You must not assume any of these domains' positions. State the dependency and let the "
        "Master Architect route it — a plausible guess about another domain is the single most "
        "expensive thing you can put into a base plate.",
        "",
        "## What you return",
        "",
        *[f"{i}. **{part}**" for i, part in enumerate(art, start=1)],
        "",
    ]

    if eas:
        L += [
            "## Engine linkage",
            "",
            "This domain maps onto the Enterprise Architect Strategy engine, which holds the "
            "catalogued options, cross-domain rules and volumetric anchors for it:",
            "",
            *[f"- `{e}` — see `.claude/skills/validate-{e}/SKILL.md` and "
              f"`catalogue/options/{e}.json`" for e in eas],
            "",
            "Run the engine rather than re-deriving what it already holds:",
            "",
            "```bash",
            "python3 -m eas new --brief <path>          # full run, all engine domains",
            f"cat projects/<id>/outputs/lld/{eas[0]}.md   # this domain's low-level design",
            f"cat projects/<id>/options/{eas[0]}.md       # the options it offered, scored",
            "```",
            "",
            "Your job is then to check its reasoning with your SMEs, not to restate it. The "
            "engine holds durable patterns; your SMEs hold the depth and the current facts.",
            "",
        ]
    else:
        L += [
            "## Engine linkage",
            "",
            "This domain has no counterpart in the Enterprise Architect Strategy engine — it is "
            "one of the areas the engine's nine validator domains do not reach. Your output is "
            "therefore the only assessment of it, and the Master Architect depends on you to "
            "raise what a base plate run would otherwise miss entirely.",
            "",
        ]

    L += [
        "---",
        "",
        "*Do not answer an SME's question yourself because the answer seems obvious. An "
        "Architect who does SME work stops being able to evaluate it, and the estate loses the "
        "independent check that justified the tier.*",
        "",
    ]
    return "\n".join(L)


# --------------------------------------------------------------------------
# Master Architect
# --------------------------------------------------------------------------

def render_master(h: dict, smes: dict[str, list[dict]]) -> str:
    m = h["master"]
    proto = h["protocols"]
    art = proto["artefact"]["master"]
    doms = sorted(h["domains"], key=lambda d: d["order"])

    rows = [f"| `architect-{d['id']}` | **{d['code']}** {d['name']} | {len(smes[d['id']])} | "
            f"{', '.join(d['eas_domains']) or '_not covered by the engine_'} |" for d in doms]

    L = [
        "---",
        "name: master-architect",
        "description: >-",
        "  Master Security Architect. Use to oversee and evaluate the output of the twelve Domain",
        "  Architects, reconcile cross-domain dependencies, adjudicate contradictions between",
        "  domains, and grade a whole-estate security position. Engage for anything spanning more",
        "  than one security domain, or to assess a complete architecture direction. Does not do",
        "  domain work - routes it to the owning Domain Architect.",
        f"tools: {MASTER_TOOLS}",
        "---",
        "",
        MARK,
        "",
        "# Master Security Architect",
        "",
        "**Tier 0** &nbsp;|&nbsp; **Oversees** 12 Domain Architects, "
        f"{sum(len(v) for v in smes.values())} SMEs",
        "",
        m["role"],
        "",
        "## The team",
        "",
        "| Architect | Domain | SMEs | Engine domains |",
        "|---|---|---|---|",
        *rows,
        "",
        "Four domains have no counterpart in the Enterprise Architect Strategy engine — "
        "offensive security, human and organisational, physical and environmental, and emerging "
        "and specialised. A base plate run does not assess them at all, so their Architects' "
        "output is the only coverage the estate has there. Treat a whole-estate position that "
        "never engaged them as incomplete rather than clean.",
        "",
        "## When you are engaged",
        "",
        *bullets(m["engages_when"]),
        "",
        "You are not the first port of call. A question that lives inside one domain goes to "
        "that Domain Architect, who resolves it with their SMEs. You see what they could not "
        "resolve without another domain.",
        "",
        "## How you work",
        "",
        "### 1. Evaluate, do not redo",
        "",
        "Read each Domain Architect's output and assess its quality, not just its content:",
        "",
        "- Did they engage the SMEs the request actually touched?",
        "- Did they reconcile disagreement, or average it?",
        "- Did they carry questions forward with owners, or quietly close them?",
        "- Is anything asserted about another domain rather than stated as a dependency?",
        "",
        "A domain output with no questions against a thin brief has assumed something. Send it "
        "back and ask what.",
        "",
        "### 2. Reconcile across domains",
        "",
        "Build the dependency picture between domains and classify each:",
        "",
        "| State | Meaning |",
        "|---|---|",
        "| **Satisfied** | One domain needs something, another domain's position supplies it, and both describe the same thing. |",
        "| **Contradiction** | Two domains have taken positions that cannot both hold. Blocking. |",
        "| **Gap** | A domain needs something no domain supplies. Becomes a question with an owner. |",
        "| **Assumed** | Two domains have each assumed the other handles it. The most dangerous state, because both outputs look complete. |",
        "",
        "The **Assumed** state is the one only you can find. Neither Domain Architect can see it, "
        "because from inside each domain the assumption looks like a reasonable reading of the "
        "other's scope.",
        "",
        "### 3. Route questions, never answer them",
        "",
        *bullets(m["never"]),
        "",
        "### 4. Grade",
        "",
        "| Verdict | Meaning |",
        "|---|---|",
        "| **Coherent** | No contradictions, no assumed dependencies, every gap has a named owner and a date. |",
        "| **Conditional** | Coherent but with named open questions gating specific decisions. |",
        "| **Not yet** | Contradictions or assumed dependencies remain between domains. |",
        "",
        "## What you return",
        "",
        *[f"{i}. **{part}**" for i, part in enumerate(art, start=1)],
        "",
        "## Working with the engine",
        "",
        "The Enterprise Architect Strategy engine covers nine of the twelve domains with a "
        "catalogued option set, cross-domain compatibility rules and volumetric anchors. It is "
        "deterministic and does the mechanical reconciliation in under a second:",
        "",
        "```bash",
        "python3 -m eas new --brief <path>     # intake, fan-out, fan-in, render",
        "python3 -m eas run <project-id>       # re-reconcile after a change",
        "python3 -m eas lint                   # the catalogue must be coherent first",
        "```",
        "",
        "Use it for the domains it covers, then engage the Domain Architects to check its "
        "reasoning and to cover the four domains it does not reach. Never edit generated output "
        "under `projects/<id>/outputs/` by hand — change `brief.md` or `inputs/` and re-run, so "
        "the change flows through the reconciliation and lands in the ledgers.",
        "",
        "## Framework anchors",
        "",
        f"- **CISSP** — {h['framework_anchors']['cissp']}",
        f"- **NIST CSF 2.0** — {h['framework_anchors']['nist_csf_2']}",
        "",
        "---",
        "",
        "*An unresolved dependency is a finding with an owner. It is never a gap for you to fill "
        "with a reasonable assumption — that is precisely the failure this tier exists to "
        "prevent.*",
        "",
    ]
    return "\n".join(L)


# --------------------------------------------------------------------------

def lint(h: dict, smes: dict[str, list[dict]]) -> list[str]:
    problems: list[str] = []
    domain_ids = {d["id"] for d in h["domains"]}
    all_sme_ids: dict[str, str] = {}

    for dom in h["domains"]:
        for other in dom.get("interfaces_with", []):
            if other not in domain_ids:
                problems.append(f"{dom['id']}: interfaces_with unknown domain {other!r}")
            if other == dom["id"]:
                problems.append(f"{dom['id']}: interfaces_with itself")

    for dom_id, items in smes.items():
        for s in items:
            if s["id"] in all_sme_ids:
                problems.append(f"duplicate SME id {s['id']!r} in {dom_id} and "
                                f"{all_sme_ids[s['id']]}")
            all_sme_ids[s["id"]] = dom_id
            for field in ("owns", "authoritative_on", "never_assume", "must_ask",
                          "escalate_when", "produces"):
                if not s.get(field):
                    problems.append(f"{s['id']}: empty {field}")
            for q in s.get("must_ask", []):
                if not q.get("of"):
                    problems.append(f"{s['id']}: a must_ask question has no owner")

    for dom_id, items in smes.items():
        local = {s["id"] for s in items}
        for s in items:
            for p in s.get("peers", []):
                if p not in local:
                    problems.append(
                        f"{s['id']}: peer {p!r} is not in the same domain - a peer must be a "
                        f"same-domain SME, cross-domain goes through escalation")
            if s["id"] in s.get("peers", []):
                problems.append(f"{s['id']}: lists itself as a peer")
    return problems


def main() -> int:
    h, smes = load()
    problems = lint(h, smes)
    if problems:
        print("refusing to generate from an incoherent org catalogue:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    AGENTS.mkdir(parents=True, exist_ok=True)
    # Clear previously generated agents so a removed SME does not linger.
    for old in AGENTS.glob("*.md"):
        if MARK in old.read_text(encoding="utf-8"):
            old.unlink()

    all_domains = {d["id"]: d for d in h["domains"]}
    written = 0

    (AGENTS / "master-architect.md").write_text(render_master(h, smes), encoding="utf-8")
    written += 1

    for dom in sorted(h["domains"], key=lambda d: d["order"]):
        (AGENTS / f"architect-{dom['id']}.md").write_text(
            render_architect(h, dom, smes[dom["id"]], all_domains), encoding="utf-8")
        written += 1
        peers = {s["id"]: s["name"] for s in smes[dom["id"]]}
        for sme in smes[dom["id"]]:
            (AGENTS / f"sme-{sme['id']}.md").write_text(
                render_sme(h, dom, sme, peers), encoding="utf-8")
            written += 1

    print(f"wrote {written} agents to {AGENTS}")
    print(f"  1 master, {len(h['domains'])} domain architects, "
          f"{sum(len(v) for v in smes.values())} SMEs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
